### ISSUE TITLE
카카오 유저 정보 가져오기 & 로그아웃

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#11]
# 카카오 유저 정보 가져오기 및 로그아웃

## 👼 TODO:
- [x] 엑세스 토큰 정보 가져오기 
- [x] 메인(로비)화면에 왔을 때 토큰이 없으면 login 화면으로 라우팅
- [x] http 헤더에 토큰 담아서 api 호출
- [x] 유저 정보 api 연동
- [x] 로그아웃 버튼 추가
- [x] 로그아웃 처리, 토큰 제거한 뒤 로그인 화면으로 라우팅
