### ISSUE TITLE
CRDT 구현

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#12]
# 실시간 동시 편집 기능(CRDT) 구현

## 👼 TODO:
- [x] yjs 라이브러리 적용
- [x] yorkie 라이브러리 적용
- [x] yjs vs yorkie 비교
- [x] crdt 동시편집 구현
- [x] board 상태 저장할 서버와 연결 작업

📣 yjs 적용하기로 결정
