### ISSUE TITLE
konva 적용하여 toolbar 구현

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#17]
# 툴바(toolbar) 구현

## 👼 TODO:
- [x] toolbar UI, 아이콘
- [ ] toolbar에서 아이콘 선택시 해당 위젯 보드에 추가
- [ ] toolbar 요소들 - (우선순위) select, sticky note, pen, calendar, export / text, image, sticker, comment
