### ISSUE TITLE
[UI] board screen

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#2]
# 보드 메인 화면

## 👼 TODO:
- [x] 레이아웃 잡기
- [x] widget Navigation
- [x] widget 추가 버튼
- [x] workspace 이름 & board 이름
- [x] 버전 히스토리 버튼
- [x] 채팅 아이콘 버튼
- [x] board에 접속한 멤버들 프로필 목록
