### ISSUE TITLE
board yjs 적용

### ISSUE THREAD

**Issue by wnstn819** [Baby-on-top/Lignin-FE#26]
# issue title

## 👼 TODO:
- [x] div drag 적용
- [x] div yjs 적용
- [ ] div 클릭했을 때 다른 쪽에서 클릭하면 yjs 안되는 부분 수정
- [ ] drag 할 때 클릭 위치에 따라 다른 화면에서 다르게 찍히는 부분 수정
