### ISSUE TITLE
보드 생성 및 조회

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#3]
# 보드 생성 및 조회

## 👼 TODO:
- [x] 보드 생성하기 input box UI
- [x] 보드 리스트 조회 / 보드 생성 api 연동 
- [x] 저장 후 화면 갱신, board  클릭시 board screen으로 이동시키기
