### ISSUE TITLE
로비 기능 구현

### ISSUE THREAD

**Issue by doragimoochim** [Baby-on-top/Lignin-FE#30]
# issue title

## 👼 TODO:
- [ ] 워크스페이스 수정, 삭제, 탈퇴 후 리렌더링
- [ ] 모달창 종료 화면이벤트 추가
- [ ] 로비→메인화면 이동시 워크스페이스, 보드네임 반영
- [ ] 드롭다운모달 2번연속 클릭오류 해결
- [ ] 보드찾기 기능추가
- [ ] 보드찾기 UI
- [ ] 워크스페이스 +버튼 온클릭이벤트 반영
- [ ] 로비 카드 UI
- [ ] 드롭다운모달 위치 및 아이콘 변경
- [ ] 기타 CSS
