### ISSUE TITLE
로비 기능, UI, css 구현

### ISSUE THREAD

**Issue by doragimoochim** [Baby-on-top/Lignin-FE#37]
# issue title

## 👼 TODO:
- [ ] 보드 업데이트 경과 시간 기능 및 css 구현
- [ ] 보드, 워크스페이스 메뉴모달 css
- [ ] 보드초대 유저 리스트 css
- [ ] 보드검색 css
- [ ] 로비보드 css
- [ ] 워크스페이스 추가하기, 리스트 중첩오류 해결
- [ ] 채팅모달 위치오류 해결
