### ISSUE TITLE
kakao login

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#4]
# 카카오 소셜 로그인

## 👼 TODO:
- [X] 간단한 로그인 화면 구현
- [X] 버튼 누르면 카카오 로그인 띄우기
- [x] 카카오로부터 인가 코드 받아오기
- [x] 인가 코드 백엔드에 넘기고 암호화된 토큰 받기
- [x] 토큰을 로컬 스토리지에 쿠키로 저장
- [x] 로그인 완료되면 로비 화면으로 리다이렉트

+) **CORS 에러 프론트 서버 배포 후에 시도해보기 일단 보류** / 나중에 시간되면 관련내용 블로그에 업로드

**Comment by Riudiu** [comment]
CORS 에러 - response header 부분에 Access-Control-Allow-Origin 요소를 추가하도록 백엔드에게 요청하여 해결
