### ISSUE TITLE
로비 기능 구현 및 css 수정

### ISSUE THREAD

**Issue by doragimoochim** [Baby-on-top/Lignin-FE#41]
# issue title

## 👼 TODO:
- [ ] 보드 업데이트 순 정렬 기능 구현
- [ ] 워크스페이스 별 보드검색 input값 초기화 및 css오류 수정
- [ ] 헤더 css 수정
- [ ] 워크스페이스 드롭다운 아이콘 및 위치 변경
