### ISSUE TITLE
[UI] lobby screen

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#6]
# 로비 화면 UI

## 👼 TODO:
- [x] 간략한 프로필 정보
- [x] 워크스페이스 리스트
- [x] 워크스페이스 추가 버튼
- [x] 워크스페이스 이름
- [x] 보드 추가 버튼
- [x] 보드 리스트
- [x] 채팅 아이콘 버튼
