### ISSUE TITLE
워크스페이스 생성 및 조회

### ISSUE THREAD

**Issue by Riudiu** [Baby-on-top/Lignin-FE#7]
# 워크스페이스 생성 및 조회

## 👼 TODO:
- [ ] 워크스페이스 생성하기 버튼 추가
- [ ] 워크스페이스 생성하기 input UI
- [ ] 워크스페이스 조회 / 워크스페이스 생성 api 연동
- [ ] 저장 후 response 받아서 lobby screen 상태 갱신시키기
